minetest-mods/drawers

- lua/api.lua
- lua/visual.lua
This makes pipeworks more efficient, since large drawer networks can now be handled.
> Prevent items from entering drawers without room for the item

- lua/api.lua
- lua/visual.lua
This bug fixes an issue with players getting double the items they should have, since when can_insert gets called the items already get inserted.
> Fix Duplicate items bug when inserting items from pipes

- lua/visual.lua
Fix issue where storage drawer saves item name for items with max stack of 1 causing you to not be able to put in other items until breaking the drawer or reloading the game. To replicate the issue, right click on a drawer with something like a written book that has a max stack of one and then try right clicking on the drawer with an item that would normally work. It won't go in because the book name was saved in the metadata.
If you want to fix this a different way, that's fine. I figured this was the easiest thing to do. Also I've never done pull request before so I hope I'm doing it right.
> Items with max stack of 1 have name saved in metadata

- lua/controller.lua
This mod just crashed the Linuxworks server, since I didn't define the controller interval anywhere.
>  Fixed crash when drawers_controller_interval is undefined. 

- init.lua
Fixes the issue where punching a drawer in MineClone 2 would cause it to instantly break and not drop. This was due to MineClone not using the same groups as Minetest and they also use additional parameters for hardness, blast resistance, etc.
> Fix MineClone 2 draw punching bug

- lua/helpers.lua
- lua/visual.lua
I found the drawers on my server were piling up entities without getting rid of them. Using WorldEdit I found that the radius of 0.537 was too small to see the extras, and increasing it by 0.01 fixed it. I increased it by 0.03 in the PR just to make it a nice number and account for any stray entities it might find.
> Increase entity check radius by 0.03 and add automatic drawer check

- lua/controller.lua
- lua/visual.lua
I made two bug fixes. The first adds a check to make sure the inv of the drawer puncher isn't nil. I didn't realize other things in the world could even punch the drawers, but I guess so. I unfortunately couldn't test this fix. The person reporting the problem used a mod with an archer that is outdated and broken. I couldn't get the archers to do anything. In theory though it should fix it.
The second fix is adding the gui changes that were made to the drawers in the past to the drawer controller. It was using default textures and causing issues for MCL2. I see you fixed that and used the same fix for the controller. I tested it and confirmed it works in both default and MCL2.
> Nil inv and controller gui fixes

- lua/controller.lua
After fixing the previous bug for MCL2, the user tested it again and pointed out another bug. I forgot to add the MCL2 specific groups to the drawer controller. I had added them in the past to the drawers themselves but not the drawer controller. I just copied the same groups that cobble used.
> Fix MCL2 node groups for controller

- lua/helpers.lua
z-fighting is still an issue on certain coordinates.
* teleport to `-28000 10 -28000`
* places a few drawers and insert random objects
(this may be an engine issue)
This PR increases the offset-factor from `0.438` to `0.5`
> prevent z-fighting on certain coordinates

- lua/controller.lua
Controllers in unloaded/inactive areas would become jammed otherwise
> kick off sorting after pipeworks inserted an item to the controller

- lua/helpers.lua
- lua/visual.lua
Fix for #43
(cherry picked from commit 740a78c73144229f61ece818864c01f741ce4cd0)
> Increase core.get_objects_inside_radius to stop drawer visuals get recreated on every block load

- .luacheckrc
- lua/api.lua
- mod.conf
This PR registers drawers as unmovable if the `mesecons_mvps` is found.
There are visual glitches and item duplication issues otherwise.
Demonstration:
Bug reported by chi/jessicara (thanks :+1:)
https://youtu.be/9VjKvE-Jy_k
> register drawers with mvps_stopper when mesecons_mvps is available

- lua/visual.lua
Apparently the metadata was not updated with the size of a stack for an inserted item, so the percentages were wrong and the number of dropped items on change wrong for items where the maximum stack number is not 99.
In my own testing after this, it appears to not drop an obscene amount of stacks and the percentage full looks right.
Related: https://github.com/minetest-mods/drawers/issues/52
> appears to fix wrong stacking

- lua/api.lua
- lua/controller.lua
- lua/helpers.lua
- lua/visual.lua
The previously used minetest.serialize function may provide different
results for the same table in certain circumstances, thus it is not
suitable for generating strings to index tables with.
> Fix #57 by using core.hash_node_position for reliable indexing

- lua/visual.lua
> Fix crash when removing upgrades from drawer surrounded by non-air nodes

- lua/controller.lua
Fixes a bug where items from tubes would always enter the drawer controller even when it can't accept them, causing items to get stuck in tubes.
An example setup: Items should go into the drawer controller if there is room, otherwise they go into the trash. Before this fix they would instead go back to the tube they came from, because the trash has a lower priority.
> Fix controller `can_insert` function returning number instead of boolean

- lua/controller.lua
This change allows the drawer controller to add items to a new drawer if it's currently assigned drawer(s) are full.
I made some gifs of behavior before and after, but apparently the files are too big to attach. I'll attach an imgur link in a bit.
> Allow controller to store item even when current drawers are full

- lua/helpers.lua
`tile_to_image` function by HybridDog (LGPLv2.1+)
Fix for https://github.com/minetest-mods/drawers/issues/76 @lnjX
> fix crash with animated nodes (inventorycube related)

- lua/api.lua
> better inventory view in drawer formspec

- init.lua
- lua/api.lua
- lua/controller.lua
Use the same inventory layout in controller.lua than in api.lua for drawer inventory.
The inventory in mcl2 is 9 slots per row and the hotbar is displayed at the bottom.
The default game inventory is 8 slots per row and the hotbar is displayed at the top.
For consistency and make the mcl2 inventory full visible, I made larger the controller formspec size.
> Update controller inventory to be compatible with mcl2

- init.lua
- lua/api.lua
- lua/controller.lua
see https://github.com/pandorabox-io/pandorabox.io/issues/836
> drawers aren't ground content
